export type InventoryCategory = "all" | "velg" | "ban" | "kap-mesin" | "spoiler" | "rem";

export interface InventoryItem {
  id: string;
  name: string;
  category: "velg" | "ban" | "kap-mesin" | "spoiler" | "rem";
  categoryLabel: string;
  sku: string;
  price: number;
  formattedPrice: string;
  image: string;
  stock: number;
  weight: string;
  material: string;
  fitment: string;
  finish: string;
  description: string;
  specs: { label: string; value: string }[];
  features: string[];
  modelUrl?: string; // Optional path to custom 3D model (e.g. '/models/velg-apex.fbx')
}

export const INVENTORY_CATEGORIES: { id: InventoryCategory; label: string; icon: string; count: number }[] = [
  { id: "all", label: "Semua Kategori", icon: "Layers", count: 25 },
  { id: "velg", label: "Velg", icon: "Disc", count: 5 },
  { id: "ban", label: "Ban", icon: "CircleDot", count: 5 },
  { id: "kap-mesin", label: "Kap Mesin", icon: "Car", count: 5 },
  { id: "spoiler", label: "Spoiler", icon: "Wind", count: 5 },
  { id: "rem", label: "Rem", icon: "ShieldAlert", count: 5 },
];

export const INVENTORY_ITEMS: InventoryItem[] = [
  // --- VELG ---
  {
    id: "velg-1",
    name: "Mod Carbon Apex R20 Monoblock",
    category: "velg",
    categoryLabel: "Velg",
    sku: "MC-WHL-001",
    price: 42500000,
    formattedPrice: "Rp 42.500.000",
    image: "https://images.unsplash.com/photo-1611821064430-0d40291d0f0d?auto=format&fit=crop&w=800&q=80",
    stock: 4,
    weight: "8.4 kg / velg",
    material: "Forged 6061-T6 Aerospace Aluminum",
    fitment: "PCD 5x114.3 / 5x120 (Et 35-42)",
    finish: "Satin Dark Anthracite + Carbon Accents",
    description: "Velg forged monoblock super ringan dengan kekuatan struktural tinggi untuk beban sirkuit dan daily high-speed.",
    specs: [
      { label: "Diameter & Lebar", value: "20 x 9.5F / 20 x 11R" },
      { label: "Offset (ET)", value: "+38 Front / +42 Rear" },
      { label: "PCD", value: "5 x 114.3 / 5 x 120" },
      { label: "Brake Clearance", value: "Hingga 420mm CCM Rotor" },
      { label: "Sertifikasi", value: "JWL, VIA, TUV Compliant" },
    ],
    features: ["Pocket-milled spoke spokes", "Knurled bead seat cegah tyre slip", "Custom center cap carbon"],
    modelUrl: "/models/velg.gltf"
  },
  {
    id: "velg-2",
    name: "Titan GT Track Spec 19-Inch",
    category: "velg",
    categoryLabel: "Velg",
    sku: "MC-WHL-002",
    price: 36000000,
    formattedPrice: "Rp 36.000.000",
    image: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=800&q=80",
    stock: 6,
    weight: "7.9 kg / velg",
    material: "Magnesium-Aluminum Forged Hybrid",
    fitment: "PCD 5x112 / 5x114.3",
    finish: "Gloss Carbon Black Coating",
    description: "Bobot minimum dengan geometri spoke aerodinamis untuk pendinginan kaliper rem maksimal.",
    specs: [
      { label: "Diameter & Lebar", value: "19 x 8.5F / 19 x 9.5R" },
      { label: "Offset (ET)", value: "+40 Front / +45 Rear" },
      { label: "PCD", value: "5 x 112 / 5 x 114.3" },
      { label: "Center Bore", value: "66.5mm / 73.1mm" },
      { label: "Sertifikasi", value: "TUV Motorsport Tested" },
    ],
    features: ["Aero-optimized airflow spokes", "Anti-twist structural ring", "Ultralight titanium bolts included"],
    modelUrl: "/models/velg.gltf"
  },
  {
    id: "velg-3",
    name: "Carbon Barrel Modular 21-Inch",
    category: "velg",
    categoryLabel: "Velg",
    sku: "MC-WHL-003",
    price: 78000000,
    formattedPrice: "Rp 78.000.000",
    image: "https://images.unsplash.com/photo-1580274455191-1c62238fa333?auto=format&fit=crop&w=800&q=80",
    stock: 2,
    weight: "6.8 kg / velg",
    material: "Pre-preg Carbon Fiber Barrel + Forged Center",
    fitment: "Centerlock / PCD 5x130",
    finish: "2x2 Twill Gloss Carbon Fiber",
    description: "Kombinasi barrel full serat karbon pre-preg dan center face forged titanium alloy untuk performa eksotis tertinggi.",
    specs: [
      { label: "Diameter & Lebar", value: "21 x 10F / 21 x 12.5R" },
      { label: "Konstruksi", value: "2-Piece Modular Carbon/Forged" },
      { label: "PCD / Hub", value: "Center Lock & 5x130 Porsche/Supercar" },
      { label: "Bobot Rotasi", value: "-35% Unsprung Mass" },
    ],
    features: ["Carbon fiber outer rim barrel", "Titanium assembly hardware", "Heat resistant resin matrix"],
  },
  {
    id: "velg-4",
    name: "Apex Aero-Blade Forged 18-Inch",
    category: "velg",
    categoryLabel: "Velg",
    sku: "MC-WHL-004",
    price: 29500000,
    formattedPrice: "Rp 29.500.000",
    image: "https://images.unsplash.com/photo-1616422285623-13ff0162193c?auto=format&fit=crop&w=800&q=80",
    stock: 5,
    weight: "7.6 kg / velg",
    material: "Forged T6-6061 Billet",
    fitment: "PCD 5x114.3 / 5x100",
    finish: "Diamond Cut Brushed Metal with Tint",
    description: "Desain directional aero-blade yang mengalirkan udara dingin langsung ke brake duct secara konstan.",
    specs: [
      { label: "Diameter & Lebar", value: "18 x 8.5 Square" },
      { label: "Offset (ET)", value: "+35" },
      { label: "PCD", value: "5 x 114.3" },
      { label: "Brake Clearance", value: "Big Brake Kit Ready" },
    ],
    features: ["Aero directional blades", "High load fatigue rating", "Matte clear protective coat"],
  },
  {
    id: "velg-5",
    name: "Strada Superleggera Multi-Spoke 20",
    category: "velg",
    categoryLabel: "Velg",
    sku: "MC-WHL-005",
    price: 38000000,
    formattedPrice: "Rp 38.000.000",
    image: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&w=800&q=80",
    stock: 3,
    weight: "8.2 kg / velg",
    material: "High Pressure Forged Alloy",
    fitment: "PCD 5x112 / 5x120",
    finish: "Stealth Satin Carbon Grey",
    description: "10-spoke slim architecture dengan kekakuan torsi tinggi saat cornering ekstrem di kecepatan tinggi.",
    specs: [
      { label: "Diameter & Lebar", value: "20 x 9.0F / 20 x 10.5R" },
      { label: "Offset (ET)", value: "+32F / +38R" },
      { label: "PCD", value: "5 x 112" },
      { label: "Max Load", value: "780 kg / corner" },
    ],
    features: ["Deep concave profile", "Back-pocket weight reduction", "Laser-etched authenticity serial"],
  },

  // --- BAN ---
  {
    id: "ban-1",
    name: "Michelin Pilot Sport Cup 2 R",
    category: "ban",
    categoryLabel: "Ban",
    sku: "MC-TYR-101",
    price: 8900000,
    formattedPrice: "Rp 8.900.000",
    image: "https://images.unsplash.com/photo-1578844251758-2f71da64c96f?auto=format&fit=crop&w=800&q=80",
    stock: 8,
    weight: "10.2 kg / ban",
    material: "Motorsport Bi-Compound Rubber + Aramid Belt",
    fitment: "265/35 ZR20 / 305/30 ZR20",
    finish: "Velvet Matte Sidewall Premium Touch",
    description: "Ban semi-slick jalan raya tercepat dengan grip lateral lateral hingga 1.5G di aspal kering.",
    specs: [
      { label: "Ukuran", value: "265/35 ZR20 (99Y) XL" },
      { label: "Treadwear", value: "140 (Ultra High Grip)" },
      { label: "Traction / Temp", value: "AA / A" },
      { label: "Speed Rating", value: "Y (>300 km/h)" },
    ],
    features: ["Dynamic Response Technology", "Track Longevity Technology 2.0", "Homologasi supercar pabrikan"],
  },
  {
    id: "ban-2",
    name: "Pirelli P Zero Trofeo R Track Spec",
    category: "ban",
    categoryLabel: "Ban",
    sku: "MC-TYR-102",
    price: 8400000,
    formattedPrice: "Rp 8.400.000",
    image: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=800&q=80",
    stock: 10,
    weight: "10.5 kg / ban",
    material: "Motorsport Resin Compound Formula",
    fitment: "245/35 R19 / 295/30 R20",
    finish: "Race Compound Black",
    description: "Didesain spesifik untuk track day dan time attack dengan respons kemudi super presisi.",
    specs: [
      { label: "Ukuran", value: "245/35 R19 (93Y)" },
      { label: "Treadwear", value: "60 (Extreme Track Grip)" },
      { label: "Max Speed", value: "300+ km/h" },
      { label: "Optimal Temp", value: "70°C - 90°C" },
    ],
    features: ["Asymmetric tread pattern", "Reinforced shoulder blocks", "Formula 1 compound lineage"],
  },
  {
    id: "ban-3",
    name: "Toyo Proxes R888R Competition",
    category: "ban",
    categoryLabel: "Ban",
    sku: "MC-TYR-103",
    price: 5200000,
    formattedPrice: "Rp 5.200.000",
    image: "https://images.unsplash.com/photo-1549469584-569583c4ce68?auto=format&fit=crop&w=800&q=80",
    stock: 12,
    weight: "9.8 kg / ban",
    material: "High Carbon Black Polymer",
    fitment: "235/40 R18 / 265/35 R18",
    finish: "V-Groove Directional Tread",
    description: "Pilihan utama para pebalap slalom dan track attack berkat warmup time yang sangat cepat.",
    specs: [
      { label: "Ukuran", value: "235/40 R18 95W" },
      { label: "Treadwear", value: "100" },
      { label: "Pattern", value: "V-Channel High Stability" },
      { label: "Load Index", value: "95 (690 kg)" },
    ],
    features: ["GG High-grip compound", "Wide center rib responsiveness", "Enhanced dry braking force"],
  },
  {
    id: "ban-4",
    name: "Yokohama Advan A052 Extreme",
    category: "ban",
    categoryLabel: "Ban",
    sku: "MC-TYR-104",
    price: 6100000,
    formattedPrice: "Rp 6.100.000",
    image: "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=800&q=80",
    stock: 7,
    weight: "9.9 kg / ban",
    material: "MS Compound 2R with Orange Oil",
    fitment: "255/35 R19 / 275/35 R19",
    finish: "Street Legal Track Slick",
    description: "Teknologi senyawa Orange Oil eksklusif Yokohama untuk cengkeraman maksimal di aspal basah maupun kering.",
    specs: [
      { label: "Ukuran", value: "255/35 R19 (96Y) XL" },
      { label: "Treadwear", value: "200" },
      { label: "Traction", value: "AA Rating" },
      { label: "Temperature", value: "A" },
    ],
    features: ["Asymmetric sport tread", "Orange Oil micro-contact", "Ultra-rigid carcass casing"],
  },
  {
    id: "ban-5",
    name: "Continental SportContact 7 Ultra",
    category: "ban",
    categoryLabel: "Ban",
    sku: "MC-TYR-105",
    price: 4800000,
    formattedPrice: "Rp 4.800.000",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
    stock: 14,
    weight: "10.0 kg / ban",
    material: "BlackChili 3.0 Adaptive Polymer",
    fitment: "245/40 R19 / 285/35 R19",
    finish: "Matte Black Sidewall",
    description: "Kombinasi kenyamanan jalan raya dan ketajaman handling motorsport dengan kompon adaptif BlackChili.",
    specs: [
      { label: "Ukuran", value: "245/40 R19 (98Y) XL" },
      { label: "Treadwear", value: "240" },
      { label: "Speed Rating", value: "(Y) > 300 km/h" },
      { label: "Wet Braking", value: "Class A EU Label" },
    ],
    features: ["BlackChili 3rd Gen Compound", "Adaptive pattern stiffness", "Harmonic noise damping"],
  },

  // --- KAP MESIN ---
  {
    id: "kap-1",
    name: "Vented Dry Carbon GT Bonnet",
    category: "kap-mesin",
    categoryLabel: "Kap Mesin",
    sku: "MC-HOD-201",
    price: 34500000,
    formattedPrice: "Rp 34.500.000",
    image: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80",
    stock: 3,
    weight: "5.4 kg (Original: 19.8 kg)",
    material: "100% Pre-preg Autoclaved Carbon Fiber (Toray T700)",
    fitment: "BMW M3/M4 G80/G82 / Supra A90",
    finish: "High Gloss UV-Protective Clear Coat",
    description: "Kap mesin serat karbon autoclave dengan heat extraction vents fungsional yang menurunkan temperatur ruang mesin hingga 14°C.",
    specs: [
      { label: "Pengurangan Bobot", value: "-14.4 kg (-72%)" },
      { label: "Tenunan Serat", value: "2x2 Twill Weave 3K" },
      { label: "Ventilasi", value: "Twin Louver Extractor + Rain Guards" },
      { label: "Instalasi", value: "Direct Bolt-on OEM Hinges" },
    ],
    features: ["OEM Latch and Safety Catch compatible", "Removable rain tray panels", "UV radiation blocker"],
  },
  {
    id: "kap-2",
    name: "Superleggera Induction Dual-Scoop Hood",
    category: "kap-mesin",
    categoryLabel: "Kap Mesin",
    sku: "MC-HOD-202",
    price: 38900000,
    formattedPrice: "Rp 38.900.000",
    image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80",
    stock: 2,
    weight: "4.9 kg",
    material: "Full Dry Carbon Core Sandwich Nomex",
    fitment: "Nissan GT-R R35 / Porsche 992",
    finish: "Matte Satin Raw Carbon Finish",
    description: "Dual scoop NACA duct mengarahkan udara dingin langsung ke turbocharger intake system untuk performa mesin konstan.",
    specs: [
      { label: "Metode Pabrikasi", value: "Autoclave Vacuum Bagging 6 Bar" },
      { label: "Struktur Inti", value: "Nomex Honeycomb Core" },
      { label: "Suhu Toleransi", value: "Hingga 260°C" },
      { label: "Downforce Depan", value: "+18 kg @ 200 km/h" },
    ],
    features: ["Functional NACA inlet ducts", "Aerodynamic pressure relief", "Reinforced strut mounting points"],
  },
  {
    id: "kap-3",
    name: "RS Carbon Bonnet with Clear Engine Window",
    category: "kap-mesin",
    categoryLabel: "Kap Mesin",
    sku: "MC-HOD-203",
    price: 49000000,
    formattedPrice: "Rp 49.000.000",
    image: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80",
    stock: 1,
    weight: "6.2 kg",
    material: "Pre-preg Carbon Fiber + Polycarbonate Scratch-Resistant",
    fitment: "Audi RS6 / RS7 / Corvette C8",
    finish: "Gloss Mirror Clear Coat",
    description: "Desain eksklusif dengan jendela polikarbonat transparan tahan gores untuk memamerkan intake manifold dan mesin V8.",
    specs: [
      { label: "Window Material", value: "Optical Grade Polycarbonate 4mm" },
      { label: "Thermal Rating", value: "Thermal barrier seal included" },
      { label: "Weave Pattern", value: "Forged Carbon / Twill Option" },
      { label: "Bobot", value: "6.2 kg netto" },
    ],
    features: ["Scratch-resistant window coating", "Double skin structural frame", "Aerodynamic water channels"],
  },
  {
    id: "kap-4",
    name: "Aero Track Spec Lightweight Hood",
    category: "kap-mesin",
    categoryLabel: "Kap Mesin",
    sku: "MC-HOD-204",
    price: 27500000,
    formattedPrice: "Rp 27.500.000",
    image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80",
    stock: 4,
    weight: "5.8 kg",
    material: "Wet Carbon Vacuum Infusion",
    fitment: "Honda Civic Type R FL5 / GR Yaris",
    finish: "High Gloss Resin Coat",
    description: "Kap mesin aerodinamis harian dengan sirip ventilasi louvered tengah yang menjaga temperatur radiator tetap dingin.",
    specs: [
      { label: "Pengurangan Bobot", value: "-8.5 kg vs OEM" },
      { label: "Heat Reduction", value: "-9°C intake temp" },
      { label: "Ketebalan", value: "1.8mm rigid shell" },
    ],
    features: ["Bolt-on fitment", "Includes aluminum mesh vents", "No drilling required"],
  },
  {
    id: "kap-5",
    name: "Forged Marble Carbon Extreme Hood",
    category: "kap-mesin",
    categoryLabel: "Kap Mesin",
    sku: "MC-HOD-205",
    price: 41000000,
    formattedPrice: "Rp 41.000.000",
    image: "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=800&q=80",
    stock: 2,
    weight: "5.1 kg",
    material: "Chopped Carbon Fiber Forged Composite",
    fitment: "Mercedes-AMG C63 / A45S",
    finish: "Forged Marble Gloss Finish",
    description: "Tampilan marmer eksotis forged carbon dengan ketahanan benturan multi-arah yang superior.",
    specs: [
      { label: "Composite Type", value: "Isotropic Chopped Carbon Flakes" },
      { label: "Tensile Strength", value: "3.2 GPa" },
      { label: "Clear Coat", value: "PPG CeramiClear Scratch Shield" },
    ],
    features: ["Unique marbling pattern per unit", "High stiffness-to-weight ratio", "Ceramic clear protection"],
  },

  // --- SPOILER ---
  {
    id: "sp-1",
    name: "Swan Neck Carbon GT Wing 1600mm",
    category: "spoiler",
    categoryLabel: "Spoiler",
    sku: "MC-AER-301",
    price: 31000000,
    formattedPrice: "Rp 31.000.000",
    image: "https://images.unsplash.com/photo-1525609004556-c46c7d6cf023?auto=format&fit=crop&w=800&q=80",
    stock: 3,
    weight: "3.8 kg (Blade & Endplates)",
    material: "Autoclave 3K Carbon Airfoil + Billet Aluminum Stands",
    fitment: "Universal GT Mount / Porsche GT3 RS / BMW M4",
    finish: "Gloss Carbon + Matte Black Anodized Mounts",
    description: "Desain dudukan Swan Neck aerodinamis modern yang menjaga permukaan bawah sayap tetap mulus untuk downforce maksimal.",
    specs: [
      { label: "Lebar Blade", value: "1600 mm / 63 Inch" },
      { label: "Downforce", value: "+280 kg @ 240 km/h" },
      { label: "Sudut Kemiringan (AoA)", value: "0° s/d 15° Adjustable" },
      { label: "Braket Dudukan", value: "CNC Billet 7075-T6 Alloy" },
    ],
    features: ["Wind tunnel tested CFD profile", "3D curved gurney flap included", "Multi-stage angle adjustment"],
  },
  {
    id: "sp-2",
    name: "Active Aerodynamic Dual-Stage Spoiler",
    category: "spoiler",
    categoryLabel: "Spoiler",
    sku: "MC-AER-302",
    price: 45000000,
    formattedPrice: "Rp 45.000.000",
    image: "https://images.unsplash.com/photo-1541348263662-e0c8de4259ba?auto=format&fit=crop&w=800&q=80",
    stock: 2,
    weight: "5.6 kg",
    material: "Pre-preg Carbon + High Speed Stepper Actuator",
    fitment: "Universal Sports Coupe / Sedan",
    finish: "Twill Gloss Carbon Fiber",
    description: "Sayap aktif elektronik yang otomatis beradaptasi: mode low drag di lintasan lurus, dan air brake saat pengereman keras.",
    specs: [
      { label: "Kecepatan Respons", value: "0.2 detik deploy" },
      { label: "Mode Operasi", value: "Speed Sense / Braking Air-Brake" },
      { label: "Kontroler", value: "CAN-Bus Plug & Play ECU Module" },
      { label: "Downforce Maksimal", value: "+340 kg Air-Brake Mode" },
    ],
    features: ["Standalone telemetry OBD-II sensor", "Cabin switch for manual deploy", "Waterproof IP67 actuators"],
  },
  {
    id: "sp-3",
    name: "Low-Drag Sleek Carbon Ducktail",
    category: "spoiler",
    categoryLabel: "Spoiler",
    sku: "MC-AER-303",
    price: 11500000,
    formattedPrice: "Rp 11.500.000",
    image: "https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=800&q=80",
    stock: 9,
    weight: "1.2 kg",
    material: "100% Dry Carbon Fiber",
    fitment: "BMW 3/4 Series, Civic Sedan, Supra",
    finish: "Gloss or Satin Finish",
    description: "Ducktail minimalis nan agresif yang mengurangi turbulensi udara belakang bagasi tanpa menambah drag.",
    specs: [
      { label: "Instalasi", value: "3M VHB Automotive Bond (No drill)" },
      { label: "Bobot", value: "1.2 kg" },
      { label: "Drag Coefficient", value: "-0.015 Cd reduction" },
    ],
    features: ["Pre-applied 3M tape included", "Perfect OEM trunk contour fit", "Subtle raised kick-up lip"],
  },
  {
    id: "sp-4",
    name: "Clubsport 3D Carbon Racing Wing 1400mm",
    category: "spoiler",
    categoryLabel: "Spoiler",
    sku: "MC-AER-304",
    price: 24000000,
    formattedPrice: "Rp 24.000.000",
    image: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80",
    stock: 5,
    weight: "3.4 kg",
    material: "Carbon Fiber Epoxy Composite",
    fitment: "Trunk mount universal sports cars",
    finish: "Raw Carbon Matte",
    description: "Dirancang untuk mobil balap turing dan track-day, memberikan cengkeraman poros belakang yang stabil saat pengereman tajam.",
    specs: [
      { label: "Panjang Sayap", value: "1400 mm" },
      { label: "Downforce", value: "+190 kg @ 200 km/h" },
      { label: "Endplate", value: "Removable Aero Fin" },
    ],
    features: ["Lightweight hollow blade", "Quick angle pin adjusters", "Reinforcement trunk plates included"],
  },
  {
    id: "sp-5",
    name: "Rear Deck Carbon Gurney Lip Spoiler",
    category: "spoiler",
    categoryLabel: "Spoiler",
    sku: "MC-AER-305",
    price: 8500000,
    formattedPrice: "Rp 8.500.000",
    image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80",
    stock: 7,
    weight: "0.9 kg",
    material: "Pre-preg Carbon Fiber",
    fitment: "Universal Fit Hatchback & Sedan",
    finish: "Gloss 2x2 Weave",
    description: "Gurney flap tambahan untuk spoiler pabrikan, meningkatkan efisiensi aerodinamika hingga 25%.",
    specs: [
      { label: "Panjang", value: "1250 mm (Cut-to-fit)" },
      { label: "Ketebalan Flap", value: "15 mm vertical lip" },
      { label: "Bobot", value: "0.9 kg" },
    ],
    features: ["Ultra-low weight", "Universal contour flexibility", "High downforce-to-drag ratio"],
  },

  // --- REM ---
  {
    id: "rem-1",
    name: "Mod Carbon Ceramic Matrix (CCM) Kit 420mm",
    category: "rem",
    categoryLabel: "Rem",
    sku: "MC-BRK-401",
    price: 98000000,
    formattedPrice: "Rp 98.000.000",
    image: "https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=800&q=80",
    stock: 2,
    weight: "Rotors: 5.6 kg (Besi OEM: 15.2 kg)",
    material: "Carbon-Silicon Carbide Matrix Rotor + Forged Caliper",
    fitment: "Minimum Velg 20-Inch / Universal Supercar Hubs",
    finish: "Anodized Racing Cyan (#00e5ff) 6-Piston Caliper",
    description: "Sistem rem karbon keramik kelas motorsport. Bebas brake fade hingga suhu ekstrem 1000°C dengan penurunan unsprung mass 60%.",
    specs: [
      { label: "Ukuran Rotor", value: "420mm x 38mm Ventilated Ceramic" },
      { label: "Kaliper Depan", value: "Monoblock Forged 6-Piston Radiale" },
      { label: "Kaliper Belakang", value: "4-Piston + EPB Parking Caliper" },
      { label: "Brake Lines", value: "Stainless Steel Braided Teflon" },
      { label: "Operating Temp", value: "0°C s/d 1050°C" },
    ],
    features: ["Zero fade under continuous track torture", "Life expectancy up to 300,000 km", "Low dust race-spec formulation"],
  },
  {
    id: "rem-2",
    name: "AP Racing Radi-CAL 6-Pot Track Brake Kit",
    category: "rem",
    categoryLabel: "Rem",
    sku: "MC-BRK-402",
    price: 58000000,
    formattedPrice: "Rp 58.000.000",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
    stock: 4,
    weight: "3.2 kg per caliper",
    material: "Asymmetrical Forged Aluminum Caliper",
    fitment: "Velg 19-Inch ke atas / PCD 5x114.3 / 5x112 / 5x120",
    finish: "Hard Anodized Titanium Grey",
    description: "Desain bodi Radi-CAL asimetris yang merevolusi rigiditas kaliper di bawah tekanan pedal ekstrem.",
    specs: [
      { label: "Kaliper", value: "Forged 2-Piece Radi-CAL 6-Piston" },
      { label: "Rotor", value: "380mm x 36mm Floating J-Hook Discs" },
      { label: "Piston", value: "Ventilated Stainless Steel Pistons" },
      { label: "Pad Area", value: "108 cm² Pad Surface" },
    ],
    features: ["J-Hook slotted rotors for debris ejection", "Internal fluid transfer pipes", "Anti-knockback springs"],
  },
  {
    id: "rem-3",
    name: "Brembo GT-S Monoblock 4-Piston Rear Kit",
    category: "rem",
    categoryLabel: "Rem",
    sku: "MC-BRK-403",
    price: 36500000,
    formattedPrice: "Rp 36.500.000",
    image: "https://images.unsplash.com/photo-1616422285623-13ff0162193c?auto=format&fit=crop&w=800&q=80",
    stock: 5,
    weight: "2.8 kg per caliper",
    material: "Cast Monoblock Aluminum Alloy",
    fitment: "Rear Axle 18-20 Inch Wheels",
    finish: "Black Hard Anodized with Red Engraved Logo",
    description: "Keseimbangan pengereman belakang yang ideal dengan modulasi pedal responsif tanpa over-steer.",
    specs: [
      { label: "Piston Configuration", value: "4-Piston Opposed Differential Bore" },
      { label: "Rotor Size", value: "355mm x 32mm 2-Piece Drilled" },
      { label: "Brake Bell", value: "Billet 6061-T6 Aluminum Bell" },
    ],
    features: ["Racing dust seals", "Low-noise spring clips", "Direct fit adapter brackets included"],
  },
  {
    id: "rem-4",
    name: "Floating 2-Piece Slotted Carbon-Steel Rotors",
    category: "rem",
    categoryLabel: "Rem",
    sku: "MC-BRK-404",
    price: 18500000,
    formattedPrice: "Rp 18.500.000",
    image: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=800&q=80",
    stock: 8,
    weight: "7.1 kg per rotor",
    material: "High Carbon Cast Iron + Billet Hat",
    fitment: "Direct Replacement OEM BBK 380mm",
    finish: "Zinc Plated Anti-Corrosion Finish",
    description: "Piringan cakram floating dengan pin bobbins yang membiarkan cakram mengembang secara simetris saat panas tinggi.",
    specs: [
      { label: "Dimensi", value: "380mm x 34mm" },
      { label: "Desain Vane", value: "48 Curved Directional Vanes" },
      { label: "Tipe Bobbins", value: "Full Floating Drive Pin System" },
    ],
    features: ["Resists thermal warping", "Curved cooling vanes improve airflow by 30%", "Slotted surface deglazes pads"],
  },
  {
    id: "rem-5",
    name: "Endless Carbon Kevlar High-Temp Race Pads",
    category: "rem",
    categoryLabel: "Rem",
    sku: "MC-BRK-405",
    price: 6500000,
    formattedPrice: "Rp 6.500.000",
    image: "https://images.unsplash.com/photo-1580274455191-1c62238fa333?auto=format&fit=crop&w=800&q=80",
    stock: 15,
    weight: "1.4 kg / set",
    material: "Carbon-Metallic & Kevlar Sintered Compound",
    fitment: "Universal 6-Pot & 4-Pot Caliper Standard Shapes",
    finish: "Racing Blue Backplate Coating",
    description: "Kampas rem performa tinggi dengan koefisien gesek stabil 0.48 - 0.58 μ dari suhu 50°C hingga 800°C.",
    specs: [
      { label: "Rentang Temperatur", value: "50°C - 800°C" },
      { label: "Koefisien Gesek", value: "0.48 - 0.58 μ" },
      { label: "Bahan", value: "Carbon Kevlar Sintered" },
    ],
    features: ["Linear initial bite feel", "Exceptional rotor wear characteristics", "Anti-squeal titanium shims"],
  },
];
